[variables]
  NODE_VERSION = "18"

[phases.setup]
  nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
  cmds = [
    "cd apps/backend",
    "rm -f package-lock.json",
    "npm install --only=production"
  ]

[phases.build]
  cmds = [
    "cd apps/backend", 
    "npm run build"
  ]

[start]
  cmd = "cd apps/backend && npm start"