[variables]
  NODE_VERSION = "18"

[phases.setup]
  nixPkgs = ["nodejs_18", "npm-9_x"]
  aptPkgs = ["..."]

[phases.install]
  dependsOn = ["setup"]
  onlyIncludeFiles = ["apps/backend"]

[phases.build]
  dependsOn = ["install"]  

[start]
  cmd = "npm start"

[build.env]
  NODE_ENV = "production"