[variables]
  NODE_VERSION = "18"

[phases.setup]
  nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.install]
  cmds = [
    "rm -f package-lock.json",
    "npm install --only=production"
  ]

[phases.build]
  cmds = ["npm run build"]

[start]
  cmd = "npm start"